name: Build Thesis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install TeX Live
      run: |
        sudo apt install -y texlive texlive-full
    - name: Build
      run: |
        cd build && make
